runtime: nodejs16

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6
env_variables:
  SECRET: "my-secret-value"
  NODE_ENV: "production"

entrypoint: npm start
